### ISSUE TITLE
how to get cleantext used in data-pipeline?

### ISSUE THREAD

**Issue by NathanWang7** [pipiku915/FinMem-LLM-StockTrading#10]
A package named "cleantext" is used in several .py files in data-pipeline,
for example: "./data-pipeline/01_SEC_API_10k10q_download.py",
line 8: `from cleantext import clean`,
line 226:
 ```
return clean(
        ret_txt,
        fix_unicode=True,
        to_ascii=True,
        lower=True,
        no_line_breaks=True,
        )
```
I tried to get [cleantext](https://github.com/prasanthg3/cleantext) via `pip install cleantext`, but the params of cleantext.clean() couldn't match the code in line 226.

**Comment by Carolyn-Jiang** [comment]
Please install the package use

!pip install clean-text

**Comment by NathanWang7** [comment]
> Please install the package use
> 
> !pip install clean-text

It works, thx a lot!
