### ISSUE TITLE
How can I use the fake-sample-data?

### ISSUE THREAD

**Issue by ShaoCHis** [pipiku915/FinMem-LLM-StockTrading#14]
As I have got the zip file and unzipped it,how can I use the sample-data?It's necessary for me to fix the data path in the all py files,right?Or any else convenient approach to use the sample data?
Thank for your reply!

**Comment by Acatsama0871** [comment]
Due to the copyright issue, we can not publicize our dataset. But you can follow the step described in [here](https://github.com/pipiku915/FinMem-LLM-StockTrading/tree/main/data-pipeline) to generate one by yourself.

**Comment by waylonli** [comment]
The instruction of data creation really sucks. It's just like they make it extremely hard to reproduce on purpose. And I don't really think they answer your question as I am also facing the same issue of the absolute paths and missing files.

**Comment by Armanasq** [comment]
I have the same issue here, the data is almost not generatable. 
There are too many bugs and issue there and the instructions are vague while all the paths are wrong.

**Comment by morning-star-001** [comment]
@Armanasq  @waylonli Any progress on Data generation?

@Acatsama0871 Do you mind helping with coherent dataset generation steps
