### ISSUE TITLE
Seeking Collaboration: Working Together to Address Discrepancies in Finmen Model Reproduction Results with the Paper

### ISSUE THREAD

**Issue by Ian-IC** [pipiku915/FinMem-LLM-StockTrading#15]
Hello everyone. I am currently attempting to reproduce a paper on the Finmen model, but the reproduction results differ significantly from the paper. I am looking to collaborate with others to achieve consistent reproduction results with the paper. If you are interested in this field and willing to provide assistance, please reply to this post or send me a direct message. Thank you!

**Comment by Acatsama0871** [comment]
Merge with #16, duplicate issue
