### ISSUE TITLE
Open Source Project?

### ISSUE THREAD

**Issue by spectral-sequence** [pipiku915/FinMem-LLM-StockTrading#2]
What an amazing state-of-the-art project!

Do you plan to transform this great paper and code into an open source project/ecosystem like FinGPT? or is this just meant to be an implementation of the paper for demonstration purposes?

**Comment by Acatsama0871** [comment]
Hi, we are glad you like it. The code in this GitHub is the implementation of our proposed memory structure. 

You can see more details at [Here](https://github.com/pipiku915/FinMem-LLM-StockTrading/blob/main/puppy/memorydb.py). We included everything we could except the data we obtained from other vendors, which we cannot publicize.

**Comment by spectral-sequence** [comment]
Thank you very much. 

Of course.

Working memory appears to be the next frontier for improving agents however it is quite underrated given its potential. This paper seems to be the first in-depth article on the subject:

https://arxiv.org/abs/2312.17259

Hope that your implementation of memory structure would inspire general purpose agent developers to build a working memory module. 
It is much needed indeed.

**Comment by pipiku915** [comment]
> Thank you very much.
> 
> Of course.
> 
> Working memory appears to be the next frontier for improving agents however it is quite underrated given its potential. This paper seems to be the first in-depth article on the subject:
> 
> https://arxiv.org/abs/2312.17259
> 
> Hope that your implementation of memory structure would inspire general purpose agent developers to build a working memory module. It is much needed indeed.

Thanks for your reminder. We will add it in the citation list while we are doing the further development.
