### ISSUE TITLE
cannot download data?

### ISSUE THREAD

**Issue by QixingHuang** [pipiku915/FinMem-LLM-StockTrading#6]
when I run download-data/00_download_yfinance.py, I find some files are missing, such as "data/02_intermediate/parsed_ark.csv","data/02_intermediate/yf_data.parquet", similar problems appear when I try to download news/transcript data.

**Comment by dean-sh** [comment]
Hi, seconding this. To allow us to test your work, please update the readme with instructions on downloading the data. Thanks a lot!
------
Thanks a lot for your question. We will update a dockerzied version and data processing pipeline in very soon.

**Comment by pipiku915** [comment]
> when I run download-data/00_download_yfinance.py, I find some files are missing, such as "data/02_intermediate/parsed_ark.csv","data/02_intermediate/yf_data.parquet", similar problems appear when I try to download news/transcript data.

Hi, we have reformatted the data pipeline with detailed processing explanation, and dockerize the code, It is currently posted in main branch. Please let us know if there are further issues.

**Comment by pipiku915** [comment]
> ## Hi, seconding this. To allow us to test your work, please update the readme with instructions on downloading the data. Thanks a lot!
> Thanks a lot for your question. We will update a dockerzied version and data processing pipeline in very soon.

Hi, we have reformatted the data pipeline with detailed processing explanation, and dockerize the code, It is currently posted in main branch. Please let us know if there are further issues.

**Comment by NathanWang7** [comment]
> > ## Hi, seconding this. To allow us to test your work, please update the readme with instructions on downloading the data. Thanks a lot!
> > Thanks a lot for your question. We will update a dockerzied version and data processing pipeline in very soon.
> 
> Hi, we have reformatted the data pipeline with detailed processing explanation, and dockerize the code, It is currently posted in main branch. Please let us know if there are further issues.

Hi, when running the updated file named "01_Alpaca_News_API_download.py", it raise FileNotFoundError, saying couldn't find the data\03_primary\price_data.parquet

**Comment by wang1946may7** [comment]
Hi there, Looks like 00 download price data from yahoo finiance is missing....

**Comment by Acatsama0871** [comment]
Please see the updated data pipeline. Feel free to reopen it
