### ISSUE TITLE
How to replace gpt-4 with open source LLMs?

### ISSUE THREAD

**Issue by vinodrajendran001** [pipiku915/FinMem-LLM-StockTrading#7]
It would be helpful, if you could update README with instructions on how to run this codebase with opensource LLMs like MIXTRAL, LLAMA, etc.

**Comment by Acatsama0871** [comment]
Please see the updated dockerized version. Now, you can deploy any model as long as it can work with [TGI](https://github.com/huggingface/text-generation-inference).

**Comment by Ian-IC** [comment]
Hello, have you successfully used GPT-4 to run this project? If so, can you help me solve some related problems? Thank you very much!

**Comment by pipiku915** [comment]
no activities, issue closed.
